### ISSUE TITLE
使用您提供的junit测试，貌似死锁了，

### ISSUE THREAD

**Issue by liufeiguo** [chimmhuang/redislock#1]
![image](https://user-images.githubusercontent.com/46086269/83847179-660a8d80-a73e-11ea-9f11-30b82e7dc69b.png)
解锁操作返回的result一直为0
![image](https://user-images.githubusercontent.com/46086269/83847306-98b48600-a73e-11ea-9054-9b1da4af6c89.png)

**Comment by chimmhuang** [comment]
感谢你的回复。
这个问题我也发现了，造成的原因是，redisTemplate在 set 锁的时候，对于字符串形式的又外套了一层引号，如： ""窗口A""。因此我将设置锁的方式也改回了初期的 lua 脚本的版本。

请更改为 1.0.2 版本再试下。也欢迎提出想法😁

**Comment by liufeiguo** [comment]
谢谢您，我下载1.2版本查看下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"吃茫茫"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月5日(星期五) 下午4:08
收件人:&nbsp;"chimmhuang/redislock"<redislock@noreply.github.com&gt;;
抄送:&nbsp;"ip139施亮"<771474065@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chimmhuang/redislock] 使用您提供的junit测试，貌似死锁了， (#1)





 
感谢你的回复。
 这个问题我也发现了，造成的原因是，redisTemplate在 set 锁的时候，对于字符串形式的又外套了一层引号，如： ""窗口A""。因此我将设置锁的方式也改回了初期的 lua 脚本的版本。
 
请更改为 1.0.2 版本再试下。也欢迎提出想法😁
